version: '3.8'

networks:
  jenkins-network:
    name: jenkins

volumes:
  data:
    name: jenkins-data

services:

  jenkins:
    container_name: jenkins-dood-blueocean
    image: jenkins-dood-blueocean
    privileged: true
    user: root
    build:
      context: .
    restart: unless-stopped
    networks:
      - jenkins-network
    ports:
      - 8080:8080
      - 50000:50000
    volumes:
      - data:/var/jenkins_home
      - /usr/local/bin/docker:/usr/local/bin/docker
      - /var/run/docker.sock:/var/run/docker.sock

  ngrok:
    container_name: ngrok
    image: ngrok/ngrok
    ports:
      - "4040:4040"
    networks:
      - jenkins-network
    env_file: .env
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command: ["http", "jenkins:8080"]
