pipeline {
  agent {
    docker {
      image 'python:3.10'
    }
  }
  stages {
    stage('Do job stage') {
      steps {
        sh """
        python --version
        scho sleep_start
        sleep 20
        echo stop_stop
        """
      }
    }
  }
}