pipeline {
  agent {
    docker {
      image 'python:3.10'
    }
  }
  stages {
    stage('Do job stage') {
      steps {
        sh """
        python --version
        echo sleep_start
        sleep 10
        echo stop_stop
        """
      }
    }
  }
}